### PR TITLE
[IndexBundle] Fix sort column on condition

### PR DESCRIPTION
**Pull request by davidhoeck**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -

Throws column "sort" not found on category pages.

### CODE REVIEW

**Comment by davidhoeck** [comment]
@DaffyM please sign the CLA :-)

**Comment by DaffyM** [comment]
> @DaffyM please sign the CLA :-)

done :)

**Review by dpfaffenbauer — APPROVED** [review]

**Comment by dpfaffenbauer** [comment]
thanks a lot

**Comment by davidhoeck** [comment]
@DaffyM nice - official CoreShop contributor now! 😄

**Comment by dpfaffenbauer** [comment]
@davidhoeck Hope there is more to come ;)

**Pull request merged**
