### PR TITLE
[OrderBundle] fix usage of inherited values in backend-cart/order controllers

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  |no
| BC breaks?    | no
| Deprecations? |no
| Fixed tickets | #1459

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
@Cruiser13 can you test this please?

**Comment by Cruiser13** [comment]
@dpfaffenbauer this does fix the inheritance issue with prices but the inherited product name does not display on backend order creation.

**Comment by dpfaffenbauer** [comment]
interesting, I will check again

**Comment by dpfaffenbauer** [comment]
@Cruiser13 can you check again pls?

**Comment by Cruiser13** [comment]
@dpfaffenbauer this does fix my issue. Thank you!

**Pull request merged**
