### PR TITLE
fix: property must not be accessed before initialization

### PR DESCRIPTION
**Pull request by dkarlovi**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | N/A

Small tweaks for the GA tracking features.

### CODE REVIEW

**Comment by dkarlovi** [comment]
Failures seem unrelated? :thinking:

**Comment by dpfaffenbauer** [comment]
@dkarlovi interesting failure....

**Comment by dkarlovi** [comment]
@dpfaffenbauer yeah, I don't know what that's about? My changes are tiny and should be safe.

**Comment by dpfaffenbauer** [comment]
@dkarlovi yes, safe for sure. Might be something with Pimcore or so.... since we test against 10.x-HEAD, this things happen all the time

**Pull request merged**
