### PR TITLE
fix workflow.registry service argument

### PR DESCRIPTION
**Pull request by hethehe**
change @.workflow.registry to @workflow.registry
@.workflow.registry is no longer available from Symfony 6.4

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | none

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
@hethehe this creates a new issue now. see failing tests

**Comment by dpfaffenbauer** [comment]
@hethehe It seems that we use Workflow quite extensively throughout the code base, maybe WorkflowInterface wasn't there yet when we created it. let me know if you need some help.

**Comment by hethehe** [comment]
@dpfaffenbauer thank you, I think I have found all the Workflow classes now :). But I'm not sure how to fix:

>  An exception occurred while executing a query: SQLSTATE[42S02]: Base table   
  or view not found: 1146 Table 'coreshop_test.coreshop_store' doesn't exist 

May you have a quick look?

**Comment by dpfaffenbauer** [comment]
@hethehe CoreShop Store is fixed.

For the other issue: Pimcore added something to the MaintenanceModeHelper to check for an active Database Connection, which in this case, we don't have (https://github.com/pimcore/pimcore/commit/fa42b3ee90bbec84c8d918c509b6fe117bcbc482). They already fixed it (https://github.com/pimcore/pimcore/commit/29ced9f79af18ef4485255973b1d891026908d73), but we are stuck now until a new release is made.

**Review by dpfaffenbauer — APPROVED** [review]

**Comment by dpfaffenbauer** [comment]
🎉  thanks @hethehe

**Pull request merged**
