### PR TITLE
Disable CartStockAvailability constraint in revise action

### PR DESCRIPTION
**Pull request by solverat**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #2460 

This PR is a Proposal to fix the stock check within the revise action.

### CODE REVIEW

**Comment by solverat** [comment]
Maybe setting the `coreshop.form.type.order.payment.validation_groups` to `coreshop_revise` is better than declaring it in the controller? This Form only shows up in the revise process, so no conflicts here.

**Comment by solverat** [comment]
Another fix in my PR: The `CoreShop\Component\Order\Model\Order` not necessarily knows about the revise. Coping this constraint to `CoreShop/Bundle/CoreBundle/Resources/config/validation/Order.yml` could fix this "dependency".

**Comment by dpfaffenbauer** [comment]
> Another fix in my PR: The `CoreShop\Component\Order\Model\Order` not necessarily knows about the revise. Coping this constraint `CoreShop/Bundle/CoreBundle/Resources/config/validation/Order.yml` could fix this "dependency".

You mean the validation config for Order?

**Comment by solverat** [comment]
Yes!

**Comment by dpfaffenbauer** [comment]
@solverat For me the PR seems fine. You declared it as proposal, is anything missing?

**Comment by solverat** [comment]
@dpfaffenbauer Now it's done, if you're okay with it. I've adopted following change:

> Maybe setting the `coreshop.form.type.order.payment.validation_groups` to `coreshop_revise` is better than declaring it in the controller? This Form only shows up in the revise process, so no conflicts here.

**Review by dpfaffenbauer — APPROVED** [review]

**Pull request merged**
