### PR TITLE
Feature/gh 1209 add maximum quantity to order

### PR DESCRIPTION
**Pull request by HuppertzL**
Rebased the PR #1217 
Issue #1209

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
Stan issue should be fixed, I'll wait for the test to finish before merging it

**Comment by HuppertzL** [comment]
Tried the same in https://github.com/coreshop/CoreShop/pull/1222/commits/80974391ef6475226d87088d66434936d7d63638
but reverted it after that, because it didn't work

**Comment by dpfaffenbauer** [comment]
@HuppertzL what do you think about https://github.com/coreshop/CoreShop/pull/1222/commits/bdcf6555eb998996db3dc576682acd2dac274e05 ?

Not ideal, but stan doesn't complain anymore....

**Comment by dpfaffenbauer** [comment]
@HuppertzL Tests are passing now, can you give me feedback for my solution before I merge it pls?

**Comment by HuppertzL** [comment]
I don't have a better solution :D and this one will be solved when `AddToCartQuantity` is deprecated, therefore it's okay for me.
thanks a lot :)

**Comment by dpfaffenbauer** [comment]
thanks a lot :)

**Pull request merged**
