### PR TITLE
infra: do gitsplit on merge or release

### PR DESCRIPTION
**Pull request by dkarlovi**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | N/A

This PR introduces an automagic gitsplit done by GH actions on any push to master or a new release. We can do it on pushing to maintenance branches too, but the release is the important part (because it basically auto-releases across the entire monorepo).

### CODE REVIEW

**Comment by dkarlovi** [comment]
@dpfaffenbauer for this to work, you need to [add a new repository secret](https://github.com/coreshop/CoreShop/settings/secrets/actions/new) called `GITHUB_TOKEN`. This should then allow GH actions to push on your behalf to the target repos.

**Comment by dkarlovi** [comment]
OK, seems to work, the only missing thing should be the token and it should work, see the run here:
https://github.com/sigwinhq/CoreShop/actions/runs/3967499738/jobs/6799535815

Notice since we're generating the gitsplit config, it found some missing child repos (TestBundle here),

**Comment by dpfaffenbauer** [comment]
@dkarlovi wow, nice, I'll review that next week.

**Comment by dkarlovi** [comment]
Cool, let me know if there's any questions. \o/

**Comment by dpfaffenbauer** [comment]
@dkarlovi Can you add the following branches?

 - 2.0
 - 2.1
 - 2.2
 - 3.0

If somebody pushes to one of the workflow mentioned branches, it splits automatically? As well as Tags?

**Comment by dpfaffenbauer** [comment]
closed in favor of https://github.com/coreshop/CoreShop/pull/2183

**Pull request closed without merging**
