### PR TITLE
[Order] allow passing custom-attributes from price rules to order-item

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #2532

@EinShoppo this is not ready yet, but the basic idea behind what we discussed. The idea is to allow passing custom attributes from pricing calculation to be stored in the order, thus using them to affect price calculation from cart-price-rules. (or basically anything cart-item-related). WDYT?

It is still missing parts like persistence of attributes or the cart-price-rule-condition to not allow non-discountable.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
@EinShoppo rest is now implemented as well

**Comment by dpfaffenbauer** [comment]
@EinShoppo do you wanna give this a test?

**Comment by ThatTrick** [comment]
Hi @dpfaffenbauer,

sounds great! One of my colleagues and i are looking at this today. I think you'll get feedback from us tomorrow at the latest.

**Comment by EinShoppo** [comment]
@dpfaffenbauer: Sounds great!  One of my colleagues and I are looking at this today. I think you'll get feedback from us tomorrow at the latest.

**Comment by EinShoppo** [comment]
@dpfaffenbauer We finished our tests and it works like a charm! Big cheers and many thanks :+1:
I really like the fact that the attribute is added to the cart price rules validation automatically, because i think that this attribute should win in any case and so it's good that you don't have to set a condition manually.

A possible improvement would be to also check for the presence of the not-discountable attribute in the product price rules, but this is probably technically more difficult to implement. So you can see it more as an idea for the future.

**Comment by dpfaffenbauer** [comment]
@EinShoppo nice :). Ok, then we can merge this into the 4.1 branch. you then have to update your project to 4.1 to use that ok?

**Comment by EinShoppo** [comment]
@dpfaffenbauer We planed to update to 4.0 before, so this shouldn't be a big problem for us. Do you already know when it will be released?

**Comment by dpfaffenbauer** [comment]
@EinShoppo probably after Pimcore Inspire. Are you faster than that?

**Comment by EinShoppo** [comment]
@dpfaffenbauer: I'm not sure, but if necessary we'll have to temporarily fork or patch the 4.0 version.

**Comment by dpfaffenbauer** [comment]
@EinShoppo let's have a chat next week and discuss that, can you contact me directly?

**Pull request merged**
