### PR TITLE
ID Argument for re-index command

### PR DESCRIPTION
**Pull request by aarongerig**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no

This PR adds an argument to the `coreshop:index` command, which allows defining certain index IDs to re-index. Default stays the same: all indices get re-indexed.

Additionally, if no indices are found (either by ID lookup or `findAll` method) a message is displayed in the console.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
Don't use ID's, use names. WDYT?

**Comment by aarongerig** [comment]
Names would be great as well, what if we make both possible (IDs and names)?

**Comment by dpfaffenbauer** [comment]
sure, ok

**Comment by aarongerig** [comment]
Done

**Comment by dpfaffenbauer** [comment]
ok, can you now base the PR to the 2.1 branch?

**Pull request closed without merging**
