### PR TITLE
fix token resolver service

### PR DESCRIPTION
**Pull request by solverat**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | yes/no
| Fixed tickets | #2642

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
I'll further review this so the tests break when this happens in the future

**Comment by dpfaffenbauer** [comment]
@solverat CoreShop 3.2 is Pimcore 10 only, that service is available there: https://github.com/pimcore/pimcore/blob/v10.6.9/lib/Security/User/TokenStorageUserResolver.php

It also exists in the Pimcore 11.2 branch for CoreShop 4.x: https://github.com/pimcore/pimcore/blob/11.2/lib/Security/User/TokenStorageUserResolver.php

**Comment by dpfaffenbauer** [comment]
@solverat could it be that you are running pimcore 10.5?

**Comment by solverat** [comment]
god damnit, yes. We're on 10.5.25 on some projects. since this is a really stable version, we skipped the "deprecation release".

**Comment by dpfaffenbauer** [comment]
@solverat see: https://github.com/coreshop/CoreShop/pull/2644

we are only testing against 10.6 and therefore can only guarantee to be compatible with that. therefore we upgrade the dependencies to 10.6 only.

**Comment by dpfaffenbauer** [comment]
> god damnit, yes. We're on 10.5.25 on some projects. since this is a really stable version, we skipped the "deprecation release".

10.6.9 is also stable ;)

**Pull request closed without merging**
