### PR TITLE
Update LinkGeneratorHelperInterface.php

### PR DESCRIPTION
**Pull request by kkarkus**
I've changed this to be the same as in LinkGeneratorHelper class because it'll be easier to write own tests when you rely on the interface.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
cool, if you would just rebranch it to 2.0

**Comment by kkarkus** [comment]
@dpfaffenbauer should be ok now

**Comment by dpfaffenbauer** [comment]
@kkarkus please sign the cla

**Comment by dpfaffenbauer** [comment]
ping @kkarkus, please sign the cla

**Pull request closed without merging**
