### PR TITLE
Pimcore 11 fixes

### PR DESCRIPTION
**Pull request by dlhck**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets |

A few fixes to work with Pimcore 11

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
@davidhoeck let me know when you're done.

**Comment by dlhck** [comment]
@dpfaffenbauer yep, still a draft PR, but I needed something to visualize the current changes.

**Comment by dlhck** [comment]
@dpfaffenbauer I think that's it for the first 4.0 release ✅

**Review by dpfaffenbauer — APPROVED** [review]

**Comment by dpfaffenbauer** [comment]
thanks a lot @davidhoeck

**Pull request merged**
