### PR TITLE
[Messenger] introduce Messenger Bundle

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
| Q             | A
| ------------- | ---
| Bug fix?      |no
| New feature?  | yes
| BC breaks?    | maybe
| Deprecations? | yes
| Fixed tickets | #2093

### CODE REVIEW

**Comment by solverat** [comment]
@dpfaffenbauer: The problem in almost every messenger implemention, I've seen: Logging. Your configuration will retry five times - but in 99% of all cases, it won't get better, if an exception has occurred the first time.

Which means, it is impossible to fetch invalid mail configuration, for example. I would suggest a default coreshop application logger instance.

```yaml

services:
    pimcore.coreshop_notification_logger:
        public: true
        class: Pimcore\Log\ApplicationLogger
        calls:
            - [addWriter, ['@Pimcore\Log\Handler\ApplicationLoggerDb']]
            - [setComponent, ['coreshop_notification']]
```

This service can be injected by `LoggerInterface $coreshopNotificationLogger` in a dedicated middleware or just simple by wrap each `$this->ruleApplier->applyRule()` into a try/catch block.

**Comment by dpfaffenbauer** [comment]
@solverat 
https://symfony.com/doc/current/messenger.html#saving-retrying-failed-messages
or
https://symfonycasts.com/screencast/messenger/sent-received-logging
or 
https://symfony.com/doc/current/messenger.html#multiple-failed-transports

**Comment by dpfaffenbauer** [comment]
Logging is quite a serious task and CoreShop cannot completely handle it. We, for example, use Cloud Logging. Others use Loki or elk or manually check logs.

**Comment by dpfaffenbauer** [comment]
@solverat this introduces application logger logging and MessengerBundle with a nice gui: https://github.com/pimcore/pimcore/discussions/13567

**Comment by solverat** [comment]
@dpfaffenbauer NICE!

**Pull request merged**
