### PR TITLE
[Core] Fix: ProductRepository: Added missing placeholder

### PR DESCRIPTION
**Pull request by lukadschaak**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -

Was a pull request some time ago. So this is "The Return of the Jed...", I mean: This is a new try ;-)

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
please rebase to 2.2, 2.0 is not maintained anymore

**Comment by dpfaffenbauer** [comment]
your fix is legit and works. CI just has a problem installing mysql.

**Comment by dpfaffenbauer** [comment]
thanks a lot @lukadschaak

**Comment by lukadschaak** [comment]
Yeah pipelines.. we all know it.. Thank for merging :+1:

**Pull request merged**
