### PR TITLE
[Menu] fix standalone used menus

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  |no
| BC breaks?    | no
| Deprecations? |no
| Fixed tickets | #2374

### CODE REVIEW

**Comment by dkarlovi** [comment]
@dpfaffenbauer did you grep the entire folder for the plugin use maybe?

**Comment by dpfaffenbauer** [comment]
@dkarlovi ?

**Comment by dkarlovi** [comment]
@dpfaffenbauer I mean, are these the only files where the old API is used? :)

**Comment by dpfaffenbauer** [comment]
@dkarlovi only ones I found with Search ;)

**Pull request merged**
