### PR TITLE
[Orders] Carrier name not shown with legacy serialization

### PR DESCRIPTION
**Pull request by ramundomario**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #1540

### CODE REVIEW

**Comment by ramundomario** [comment]
Stan complains... Could we check if shipment is instance of `CarrierAwareInterface`.
Wdyt? @dpfaffenbauer

**Comment by dpfaffenbauer** [comment]
I think it is better to move that part of the code to the CoreBundle

**Comment by ramundomario** [comment]
Do you mean to move the entire `getShipments` function inside the CoreBundle or add the `carrierName` as done here for each shipment?
https://github.com/coreshop/CoreShop/blob/3937a14610fa0b7dc4f498ea2d711c3e2b5fc468/src/CoreShop/Bundle/CoreBundle/Controller/OrderController.php#L45-L51

**Comment by dpfaffenbauer** [comment]
just your change

**Review by dpfaffenbauer — APPROVED** [review]

**Comment by dpfaffenbauer** [comment]
thanks :)

**Pull request merged**
