### PR TITLE
[WIP] split customer and user into seperate entities

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | yes
| Deprecations? | yes
| Fixed tickets | #665

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
This potentially makes the Members Integration easier as well (https://github.com/coreshop/CoreShop/issues/186)

**Comment by solverat** [comment]
I still don't get it... What are the real benefits here?

**Comment by dpfaffenbauer** [comment]
- A guest is a customer, but not a user. A guest currently has ROLES and is logged into the firewall.
 - Integration with something like Members is now done with the Users Component/Bundle, so we don't need to care about Guests as well
 - You can convert a guest customer to a full customer by just adding a user to it

**Comment by dpfaffenbauer** [comment]
will not happen for now. as discussed internally

**Pull request closed without merging**
