### PR TITLE
prevents recursion if href-elements contain entities of Class CoreShopProduct

### PR DESCRIPTION
**Pull request by smaier**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no

prevents recursion if href-elements contain entities of Class CoreShopProduct.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
1. please rebase on 2.0 branch
2. I don't feel like thats a definite solution, since this can also happen with other entities. Better to introduce a recursion detection.

**Comment by dpfaffenbauer** [comment]
actually, this is completly wrong anyway, since CoreShop itself doesn't really know `DataObject\CoreShopProduct`

**Comment by solverat** [comment]
Also: Could be any other product class eg. `DataObject\MySpecialProduct` or even mlutiple product classes.

**Comment by smaier** [comment]
so `instanceof \CoreShop\Component\Core\Model\Product` would be the way to go?

**Pull request closed without merging**
