### PR TITLE
Add info about coreShopStore fieldtype

### PR DESCRIPTION
**Pull request by Cruiser13**
Propose to add info about working with the coreShopStore fieldtype because it differs from pimcores many-to-types. Docs only.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
I am pretty sure you can do both, the ID and the Store object itself

**Comment by Cruiser13** [comment]
That's actually not the case (took us hours to debug it in our special situation) so I thought we might add it to the docs.

**Comment by dpfaffenbauer** [comment]
are you sure? CoreShop uses that all over the place....

Except is the coreShopStore**s** type, where it only accepts ID's

**Comment by Cruiser13** [comment]
Yes. The following does not work:

```php
public function changeStoreAction(ShopperContext $shopperContext, StoreRepositoryInterface $storeRepository){
$customer = $shopperContext->getCustomer();
$store = $storeRepository->find(2);
$customer->setCurrentstore($store);
}
```
This does:
```php
public function changeStoreAction(ShopperContext $shopperContext, StoreRepositoryInterface $storeRepository){
$customer = $shopperContext->getCustomer();
$store = $storeRepository->find(2);
$customer->setCurrentstore($store->getId());
}
```

Customer class does hold a field of type coreShopStore with the id currentstore.

**Comment by dpfaffenbauer** [comment]
I can't confirm that, I tried following:

```php
$store = $this->container->get('coreshop.repository.store')->findStandard();

        $test = new Test2();
        $test->setName("blub");
        $test->setStore($store);
        $test->setParentId(1);
        $test->setKey('test');
        $test->save();
```

Where store is a CoreShop Store Select Field.

**Comment by Cruiser13** [comment]
Very strange, it does not work for me with my code. Nevermind in this case.

**Pull request closed without merging**
