### PR TITLE
Updated CachedStoreContext.php

### PR DESCRIPTION
**Pull request by averatec1337**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no

Let's say given site doesn't have store assigned, and there's no Standard store.
It leads to many unnecessary queries to the database.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
@kamil-karkus please also sign the cla

**Comment by dpfaffenbauer** [comment]
could also backport this to the 3.2 branch? I think we should add that there as well

**Comment by dpfaffenbauer** [comment]
other than that, its fine 👍

**Comment by averatec1337** [comment]
> could also backport this to the 3.2 branch? I think we should add that there as well

https://github.com/coreshop/CoreShop/pull/2565

**Comment by dpfaffenbauer** [comment]
I'll close this since we merge up from 3.2 anyway

**Pull request closed without merging**
