### PR TITLE
[Payment] when payment is authorized or paid, order get's confirmed

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #2615

Current Issue is that:
 1. `UpdateOrderStateExtension` never updates to order state cause the payment state got changed before
 2. if you manually executed the `pay` transition, order is stuck in `new` and does not get confirmed

This PR automatically `confirms` the order when a single payment is partially paid, fully paid, partially authorized or fully authorized.

@solverat I would like to get your opinion on this.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
@solverat We would like to get your Feedback on this.

**Comment by solverat** [comment]
I'm afraid of this.

**Comment by solverat** [comment]
Funny! We just experienced this behavior in one of our new shops (not in manually mode but by payum / client workflow).

image

I'm unable to reproduce it, though...

Not sure, if this is true: 

> UpdateOrderStateExtension never updates to order state cause the payment state got changed before

The only difference now is, that the callback happens after a transition instead of the payum extension. If we're dealing with a sort of race condition here, this PR could be an improvement, since the order transition will be dispatched at the end of the payum cycle.

**Comment by dpfaffenbauer** [comment]
@solverat so not afraid anymore? :D

**Comment by solverat** [comment]
I guess not 😀

**Comment by dpfaffenbauer** [comment]
@solverat the main issue that this tries to solve is, when a user exists the payment workflow just before we come back to the payum capture/authorize route, and there is no async implemented, you never know the status of the payment. if you then manually confirm it in the backend using the payment workflow, the order never gets confirmed. this fixes that. 

We actually could reproduce it. We looged at the access logs of these orders (based on timestamps) and saw they never returned from the PSP to the shop.

**Pull request merged**
