### PR TITLE
[Tracking] add docu for setting storeValues

### PR DESCRIPTION
**Pull request by lukadschaak**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -

Hey Dominik, can you please take a look, if this way of updating storeValues is intended, or is it crap?
I wrote it in style of documentation, so when the code may be alright it can used later by other people.

I found no docu about the store values at all.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
settting the store values is right, but I don't see the point about it with tracking? I mean, if you want to sell a product, it should have a price...

**Comment by lukadschaak** [comment]
We configure our prices via the tab "Price Rules". Per product we create a quantity price rule with a Stückmengenpreisregel from 1 piece. But this price is not stored in the store values.
Are our prices maybe misconfigured?

-- german version
Wir setzen unsere Preis über den Reiter Price Rules. Wir haben pro Product eine Quantity Price Rule mit einer Stückmengen Preisregel ab 1 Einheit. Aber dieser Preis taucht nicht in den storeValues auf.
Ich war davon ausgegangen, dass dieser Preis auch in die storeValues geschrieben wird, aber dort steht nichts. Vielleicht haben wir unsere Preise falsch konfiguriert?!

grafik
grafik
grafik

**Comment by dpfaffenbauer** [comment]
this is one possible way of configuring it... coreshop has many use case for things like that.

what is the effect you experience with not having a store-price? you don't get a price at all in tracking?

**Comment by lukadschaak** [comment]
Exactly. The ProductPriceCalculator returns an error for not having store values for the requested product (there are no store values at all). And theirfor the price is always 0 as fallback.

Currently i try to find out how the price is determined for cartItems. Because there was never a problem with having no prices.

**Comment by dpfaffenbauer** [comment]
I see. The ProductPriceCalculator is one of the price-calculators. But: Quantity Price Rules are different, they don't get calculated for a product, but only for the cart. Usually you would have a "default" price in store values, and all quantity-price-rules starting with a special discount. Like default price is 10€, but starting from 10, it is 9€.

**Comment by lukadschaak** [comment]
Ahh, that would make sense.
After a bit of research: Our Team get the prices for a product by creating temporary cartItems, push them to the cart and using the '@coreshop.cart_processor' to calculate prices. And then it happens what you said before. For carts, the quantity-price-rules are used in the caluculation.

So what would be best practice to create the default values for a store? Simply setting the values via PHP Code (`$product->setStoreValuesOfType('price', 1234, $store);`)?

But then the price is not visible for pimcore backend user. Is there a way of setting the default price per store via the pimcore backend? Or at least the default price for all stores :)

**Comment by dpfaffenbauer** [comment]
for tracking you should extend the Trackings ProductExtractor to do what you already do with the price display.

**Comment by lukadschaak** [comment]
Ok, thanks :+1:

**Pull request closed without merging**
