### PR TITLE
[FrontendBundle] make reset password url absolute

### PR DESCRIPTION
**Pull request by ktallafus**
The default parameter for generateUrl is UrlGeneratorInterface::ABSOLUTE_PATH, not ABSOLUTE_URL

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
doesn't Pimcore Mail already do that?

**Comment by ktallafus** [comment]
no, when I tested it, it didn't do that

**Comment by dpfaffenbauer** [comment]
have you set the main-domain in pimcore settings?

**Comment by ktallafus** [comment]
It wasn´t, but when I set it, the link is still not absolute

**Comment by dpfaffenbauer** [comment]
alright, I'll merge it, but its something that pimcore somehow already does as well.

**Comment by dpfaffenbauer** [comment]
thanks @ktallafus

**Comment by ktallafus** [comment]
I also asked solverat about this, but he said "nicht dass ich wüsste nein" ;)
thanks!

**Comment by dpfaffenbauer** [comment]
well, so he doesn't know about it: https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Mail.php#L729

**Comment by ktallafus** [comment]
Yes, you´re right. I debugged it. But it seems like the hostUrl has to be given as option to the Mail constructor:
https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Mail.php#L198

This doesn´t happen here:
https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Component/Notification/Rule/Action/MailActionProcessor.php#L47

So... it seems my commit was wrong :(

**Comment by dpfaffenbauer** [comment]
Not completely right either: Pimcore has a "fallback" for that: https://github.com/pimcore/pimcore/blob/856e9bf14c19d82dc2bd48b762e1f9435b7bef14/pimcore/lib/Pimcore/Helper/Mail.php#L229

**Comment by ktallafus** [comment]
Ok, I got it. The problem was the link itself. I made the link in wysiwyg and it prepended the http:// protocoll. So the href ended up as http:///customer/password-reset (notice the three slashes). So Pimcore couldn´t identify it as link. If i select the protocoll to "Other", it works.

So, are you going to revert this?

**Comment by dpfaffenbauer** [comment]
thanks for looking deeper into that, I now reverted the PR. Thanks anyway :)

**Pull request merged**
