### PR TITLE
[fix] productDetailFancy thumbnail: contain -> scaleByWidth

### PR DESCRIPTION
**Pull request by myrdd**
compare https://github.com/coreshop/CoreShop/commit/41581c08c9#r30803205

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | –

### CODE REVIEW

**Comment by myrdd** [comment]
Thanks for merging so quickly, as always. :)
I've tested it on a fresh installation (using the coreshop demo data), and `pimcore:thumbnails:image` now runs and completes without errors.

BTW, what would I need to do to apply the changed `image-thumbnails.yml`? I tried `coreshop:install` and `pimcore:bundle:enable CoreShopCoreBundle`, but `pimcore:thumbnails:image` still failed afterwards.

**Comment by dpfaffenbauer** [comment]
manually, there is intentionally no update mechanism to enforce this changes

**Comment by myrdd** [comment]
> manually, there is intentionally no update mechanism to enforce this changes

I see, I just discovered `var/config/image-thumbnails.php`.

**Comment by dpfaffenbauer** [comment]
Or in the Pimcore Backend

**Pull request merged**
