### PR TITLE
Docs should comply with readme

### PR DESCRIPTION
**Pull request by Cruiser13**
docs only

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
can you base this PR on the 2.0 branch pls? master is already the dev branch for 2.1

**Comment by dpfaffenbauer** [comment]
ping @Cruiser13

**Comment by Cruiser13** [comment]
@dpfaffenbauer sorry, not sure what you mean.

**Comment by dpfaffenbauer** [comment]
your change has to be merged into the 2.0 branch. Your PR has the history of the master branch, so if I (or you) change the base branch to 2.0, it would merge the history of master into 2.0. We don't want that.

You have two options: Remove this PR and create a new one which is a branch of 2.0, or rebase your branch to 2.0.

**Pull request closed without merging**
