### PR TITLE
Translate tax display

### PR DESCRIPTION
**Pull request by Cruiser13**

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
thats not the right way to do it, this could cause issues when using different languages. a better approach would be something like:

Key: ```coreshop_product_tax_inc```
Value: ```incl. %s VAT```

So, it would be written like this:

```
'coreshop_product_tax_inc|trans|format(product|coreshop_product_tax_rate) 
```

**Comment by dpfaffenbauer** [comment]
Can you add the translation definition as well? https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml

**Comment by dpfaffenbauer** [comment]
ping @Cruiser13 can you please add the missing translations here?

https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml

**Comment by Cruiser13** [comment]
Bulk translations added here
https://github.com/coreshop/CoreShop/pull/358

**Comment by dpfaffenbauer** [comment]
thank you :) 🍻

**Pull request merged**
