### PR TITLE
[IndexBundle] Elasticsearch

### PR DESCRIPTION
**Pull request by IvanJavorovic**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no

Work in progress Elasticsearch functionality added to Indexing and Filters.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
@IvanJavorovic did this every work for you? I just tried it again and its missing lots of stuff. I will commit my changes. If you still want to complete this

**Comment by dpfaffenbauer** [comment]
I'll close, if you want to continue, please let me know

**Comment by NiklasBr** [comment]
Please don't delete the branch (unless really needed), I would like to make an attempt at getting it up and running, but it will be a few more weeks before I can make any progress.

**Comment by dpfaffenbauer** [comment]
@NiklasBr Branch is on Ivan sides, I still have it locally as well. If you are ready and dont find it anymore. let me know.

**Pull request closed without merging**
