### PR TITLE
fix price_rule migration section

### PR DESCRIPTION
**Pull request by solverat**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | --

### CODE REVIEW

**Comment by jdreesen** [comment]
What's the difference between the branches `3.0` and `master`?

Because this was already fixed in `master` in #2145 (except for the `childs` -> `children` renaming).

**Comment by solverat** [comment]
@jdreesen, true this issue has been resolved already, good catch. 
Why 3.0? I don't know why there is 3.0 branch at all. :)

**Comment by dpfaffenbauer** [comment]
CoreShop master is 3.1, 3.0 is bug fixes for 3.0.x

**Review by dpfaffenbauer — APPROVED** [review]

**Comment by dpfaffenbauer** [comment]
thanks @solverat

**Comment by jdreesen** [comment]
Then `childs` should probably also be renamed to `children` in master (or will `3.0` be merged into `master`?)

And there was an additional fix in `master` that's possibly missing in `3.0`: #2148

**Comment by jdreesen** [comment]
> CoreShop master is 3.1, 3.0 is bug fixes for 3.0.x

Also: #2148 is in the `3.0.3` milestone, which is wrong because it was merged in `master`.

**Comment by dpfaffenbauer** [comment]
3.0 will always get merged upstream to master, master will not be merged downstream to 3.0. Changed the milestone for #2148

**Comment by jdreesen** [comment]
So should #2148 also be backported to `3.0` then?

**Comment by dpfaffenbauer** [comment]
@jdreesen yes, I can cherry pick it later

**Pull request merged**
