### PR TITLE
Add some translations

### PR DESCRIPTION
**Pull request by Cruiser13**

### CODE REVIEW

**Comment by solverat** [comment]
hey @Cruiser13: `coreshop.form.customer.newsletter.unsubscribe` and `coreshop.form.customer.newsletter.no_interaction` are not available any more (see https://github.com/coreshop/CoreShop/commit/e1f3da6bda8bc8cf2be9ee4d8ab5bce327ad947d)

**Comment by Cruiser13** [comment]
Thanks @solverat 
This repo is changing way too fast to keep up with it for me.

**Comment by dpfaffenbauer** [comment]
thank you 🍻

**Comment by solverat** [comment]
@Cruiser13: yes, and that's not good at all even it means fast development. But we're heading to Beta and hopefully we'll find some refactor peace with it :).

**Pull request merged**
