### PR TITLE
[Order] fix cart item events and add missing events for "addItem" action

### PR DESCRIPTION
**Pull request by davidhoeck**
| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #1336

This PR adds the following events: 
- `coreshop.cart.pre_remove_item`
- `coreshop.cart.post_remove_item`
- `coreshop.cart.pre_add_item`
- `coreshop.cart.post_add_item`

The old events on removing an item have been kept for BC reasons.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
We should not do this anymore in 2.2. Can you rebase to master, add docs/changelog and remove the BC layer?

**Comment by davidhoeck** [comment]
> We should not do this anymore in 2.2. Can you rebase to master, add docs/changelog and remove the BC layer?

ok - so basically all the future PRs should be based on `master` until 3.0 is released?

**Comment by dpfaffenbauer** [comment]
> > We should not do this anymore in 2.2. Can you rebase to master, add docs/changelog and remove the BC layer?
> 
> @dpfaffenbauer ok - so basically all the future PRs should be based on `master` until 3.0 is released?

New Features and Breaking changes, yes. Bugfix are still valid for 2.2

**Comment by dpfaffenbauer** [comment]
closed due to inactivity

**Pull request closed without merging**
