### PR TITLE
Composer compatibility with Coreshop 2.1 series

### PR DESCRIPTION
**Pull request by Cruiser13**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no

Solves errors like Class 'CoreShop\Component\Address\Model\StateInterface' does not exist after a composer update.

I know that the 2.1 series is old but this could be worth a release in my opinion.

### CODE REVIEW

**Comment by Cruiser13** [comment]
We'd actually need to also remove Versions::VERSIONS constant as it's no longer available. Not sure how the getComposerPackageName functions in CoreShopFrontendBundle.php and CoreShopIndexBundle and so on are used but this needs change too.

**Comment by dpfaffenbauer** [comment]
CoreShop 2.1 does not receive updates anymore, if you need it, use Composer v1

**Comment by dpfaffenbauer** [comment]
also the issue with StateInterface goes not get merged into 2.1. downgrade doctrine to make it work...

**Comment by Cruiser13** [comment]
@dpfaffenbauer there are hosts which will auto update composer. Not having the 2.1 coreshop work in these environments is a huge issue. If downgrading doctrine will work, could we add that to the docs somewhere?

**Comment by solverat** [comment]
@Cruiser13 really? You should consider switching such providers then. Imagine older installations with unstable/incomplete psr-4 standard. They simply can't update, and they simply will break after a composer install on v2.

**Comment by Cruiser13** [comment]
@solverat that's sadly nothing I can personally change. Out of my hands.

**Comment by Cruiser13** [comment]
> 
> 
> CoreShop 2.1 does not receive updates anymore, if you need it, use Composer v1

I'd not create new features for 2.1 but breaking changes should be addressed I think. Updating 2.1 to 2.2 is error prone so there are a lot of 2.1 versions out there. They'll stop working with the next composer update, even if they do not update coreshop itself.

**Comment by dpfaffenbauer** [comment]
@Cruiser13 no, simply not. I don't have the time or the resources to support older versions.  Sorry, but that is out of my hands.

**Pull request closed without merging**
